version: '3.3'

services:
  code-server:
    image: jdelemar/lscr.io/linuxserver/code-server:amd64-4.19.0-ls182-icu-dotnet6
    # image: lscr.io/linuxserver/code-server:amd64-4.18.0-ls181-icu
    container_name: code
    environment:
      - TZ=America/New_York
      - SUDO_PASSWORD=Str0ngP@ssw0rd
      - DEFAULT_WORKSPACE=/config/workspace #optional
    # volumes:
    #   # Overwrites existing
    #   - /Volumes/AppData/Programming/Docker/VSCode/Code-Server/config:/config
    #   # # Try below or use: docker cp config/. code:/config
    #   # #  To copy tar.gz config: docker cp code:/config/vscode-config-231119.tgz .
    #   # - /Volumes/AppData/Programming/Docker/VSCode/Code-Server/config/data/User/settings.json:/config/data/User/settings.json
    #   # - /Volumes/AppData/Programming/Docker/VSCode/Code-Server/config/data/User/keybindings.json:/config/data/User/keybindings.json
    #   # - /Volumes/AppData/Programming/Docker/VSCode/Code-Server/config/workspace:/config/workspace
    #   # - /Volumes/AppData/Programming/Docker/VSCode/Code-Server/config/.bashrc:/config/.bashrc
    ports:
      - 8443:8443
    restart: unless-stopped
  # docker-compose build db
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU22-ubuntu-20.04
    container_name: db
    hostname: db
    environment:
      SA_PASSWORD: "Str0ngP@ssw0rd"
      ACCEPT_EULA: "Y"
    # ports:
    #  - 1433:1433
    volumes:
      - mssql_rebusdemo:/var/opt/mssql

volumes:
  mssql_rebusdemo:
